$(document).ready(function(){
  $("#icon1").click(function(){
        $(".hidden1").toggle();
    });
  $("#icon2").click(function(){
        $(".hidden2").toggle();
    });
  $("#icon3").click(function(){
        $(".hidden3").toggle();
    });
  $("#icon4").click(function(){
        $(".hidden4").toggle();
    });
});